Python-DS-AI-Batch-7/Notebooks/Week6
/sample Google Play Store data.ipynb

In [ ]:
import numpy as np
import pandas as pd

In [20]:
import pandas as pd
import numpy as np

# Generating sample Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [22]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Education', 'Education', 'Education', 'Education', 'Education',
        'Productivity', 'Game', 'Productivity', 'Health', 'Game', 'Game',
        'Game', 'Productivity', 'Health', 'Game', 'Productivity',
        'Productivity', 'Health', 'Productivity', 'Game', 'Education',
        'Health', 'Education', 'Education', 'Health', 'Productivity',
        'Productivity', 'Health', 'Health', 'Education'], dtype='<U12'),
 'Rating': array([5. , 4.8, 2.2, 2.7, 1.1, 4.7, 1. , 2. , 1.1, 1.3, 1.8, 4.2, 1.5,
        2.3, 3.3, 3.1, 2.6, 3.7, 1.2, 2.4, 3.6, 3.7, 2.7, 1.7, 2.4, 1.8,
        2.3, 1.1, 3.8, 4.3]),
 'Reviews': array([5112, 6388,  881, 6535, 3464, 5331,  938, 1916, 1594, 2356, 1285,
        4672, 8249, 7288, 9398, 1551, 7570, 9058, 8800, 6859, 5304, 5337,
         394, 3377, 6924, 5113, 5501, 7424, 3542, 4187]),
 'Size': array(['20M', '10M', '20M', '10M', 'Varies with device', '10M', '10M',
        '10M', '20M', '20M', '20M', '10M', '20M', '20M', '30M', '30M',
        '30M', '10M', '10M', '30M', '20M', '20M', '20M', '10M', '20M',
        '20M', '20M', 'Varies with device', '10M', 'Varies with device'],
       dtype='<U18'),
 'Installs': array(['50,000+', '10,000+', '1,000+', '50,000+', '50,000+', '100,000+',
        '50,000+', '100,000+', '50,000+', '50,000+', '100,000+', '10,000+',
        '10,000+', '50,000+', '10,000+', '100,000+', '100,000+', '1,000+',
        '10,000+', '50,000+', '10,000+', '100,000+', '100,000+', '10,000+',
        '1,000+', '1,000+', '10,000+', '1,000+', '10,000+', '1,000+'],
       dtype='<U8'),
 'Type': array(['Free', 'Free', 'Free', 'Free', 'Free', 'Free', 'Free', 'Free',
        'Free', 'Paid', 'Free', 'Paid', 'Paid', 'Free', 'Paid', 'Paid',
        'Paid', 'Free', 'Paid', 'Free', 'Paid', 'Paid', 'Paid', 'Paid',
        'Paid', 'Paid', 'Paid', 'Free', 'Free', 'Paid'], dtype='<U4'),
 'Price': array(['0.99', '9.99', '2.99', '9.99', '4.99', '5.99', '2.99', '4.99',
        '4.99', '0', '9.99', '1.99', '9.99', '9.99', '1.99', '0', '2.99',
        '2.99', '2.99', '1.99', '0', '5.99', '0', '0', '0.99', '9.99',
        '1.99', '1.99', '0.99', '0'], dtype='<U4'),
 'Content Rating': array(['Mature 17+', 'Teen', 'Teen', 'Mature 17+', 'Everyone 10+',
        'Mature 17+', 'Everyone', 'Everyone', 'Mature 17+', 'Everyone 10+',
        'Teen', 'Everyone 10+', 'Everyone', 'Teen', 'Teen', 'Teen',
        'Everyone', 'Teen', 'Everyone', 'Mature 17+', 'Everyone',
        'Everyone', 'Teen', 'Teen', 'Everyone 10+', 'Everyone 10+', 'Teen',
        'Everyone 10+', 'Everyone', 'Teen'], dtype='<U12')}

In [24]:
type(data)

dict

In [26]:
# Creating DataFrame
df = pd.DataFrame(data)

In [28]:
pd

In [30]:
type(df)

pandas.core.frame.DataFrame

In [32]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20M,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10M,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20M,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10M,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+

In [34]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
25,App_26,Productivity,1.8,5113,20M,"1,000+",Paid,9.99,Everyone 10+
26,App_27,Productivity,2.3,5501,20M,"10,000+",Paid,1.99,Teen
27,App_28,Health,1.1,7424,Varies with device,"1,000+",Free,1.99,Everyone 10+
28,App_29,Health,3.8,3542,10M,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,Varies with device,"1,000+",Paid,0,Teen

In [ ]:
# !pip install module name

In [36]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating'],
      dtype='object')

In [38]:
df.shape

(30, 9)

In [40]:
df['Category'].unique()

array(['Education', 'Productivity', 'Game', 'Health'], dtype=object)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             30 non-null     object
 1   Category        30 non-null     object
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32
 4   Size            30 non-null     object
 5   Installs        30 non-null     object
 6   Type            30 non-null     object
 7   Price           30 non-null     object
 8   Content Rating  30 non-null     object
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB

In [44]:
#Take sample of any 4 type
df.sample(4)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
28,App_29,Health,3.8,3542,10M,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,Varies with device,"1,000+",Paid,0,Teen
9,App_10,Game,1.3,2356,20M,"50,000+",Paid,0,Everyone 10+
17,App_18,Health,3.7,9058,10M,"1,000+",Free,2.99,Teen

In [46]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+
11,App_12,Game,4.2,4672,10M,"10,000+",Paid,1.99,Everyone 10+
22,App_23,Education,2.7,394,20M,"100,000+",Paid,0,Teen
10,App_11,Game,1.8,1285,20M,"100,000+",Free,9.99,Teen
18,App_19,Productivity,1.2,8800,10M,"10,000+",Paid,2.99,Everyone

In [48]:
df.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False

In [50]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [52]:
# Basic data cleansing
# Step 1: Convert 'Price' to numeric, replacing '$' and converting 'Free' to 0
df['Price'] = df['Price'].replace('Free', '0')

In [54]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20M,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10M,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20M,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10M,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+
5,App_6,Productivity,4.7,5331,10M,"100,000+",Free,5.99,Mature 17+
6,App_7,Game,1.0,938,10M,"50,000+",Free,2.99,Everyone
7,App_8,Productivity,2.0,1916,10M,"100,000+",Free,4.99,Everyone
8,App_9,Health,1.1,1594,20M,"50,000+",Free,4.99,Mature 17+
9,App_10,Game,1.3,2356,20M,"50,000+",Paid,0,Everyone 10+
10,App_11,Game,1.8,1285,20M,"100,000+",Free,9.99,Teen
11,App_12,Game,4.2,4672,10M,"10,000+",Paid,1.99,Everyone 10+
12,App_13,Productivity,1.5,8249,20M,"10,000+",Paid,9.99,Everyone
13,App_14,Health,2.3,7288,20M,"50,000+",Free,9.99,Teen
14,App_15,Game,3.3,9398,30M,"10,000+",Paid,1.99,Teen
15,App_16,Productivity,3.1,1551,30M,"100,000+",Paid,0,Teen
16,App_17,Productivity,2.6,7570,30M,"100,000+",Paid,2.99,Everyone
17,App_18,Health,3.7,9058,10M,"1,000+",Free,2.99,Teen
18,App_19,Productivity,1.2,8800,10M,"10,000+",Paid,2.99,Everyone
19,App_20,Game,2.4,6859,30M,"50,000+",Free,1.99,Mature 17+
20,App_21,Education,3.6,5304,20M,"10,000+",Paid,0,Everyone
21,App_22,Health,3.7,5337,20M,"100,000+",Paid,5.99,Everyone
22,App_23,Education,2.7,394,20M,"100,000+",Paid,0,Teen
23,App_24,Education,1.7,3377,10M,"10,000+",Paid,0,Teen
24,App_25,Health,2.4,6924,20M,"1,000+",Paid,0.99,Everyone 10+
25,App_26,Productivity,1.8,5113,20M,"1,000+",Paid,9.99,Everyone 10+
26,App_27,Productivity,2.3,5501,20M,"10,000+",Paid,1.99,Teen
27,App_28,Health,1.1,7424,Varies with device,"1,000+",Free,1.99,Everyone 10+
28,App_29,Health,3.8,3542,10M,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,Varies with device,"1,000+",Paid,0,Teen

In [56]:
type(df['Price'])

pandas.core.series.Series

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             30 non-null     object
 1   Category        30 non-null     object
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32
 4   Size            30 non-null     object
 5   Installs        30 non-null     object
 6   Type            30 non-null     object
 7   Price           30 non-null     float64
 8   Content Rating  30 non-null     object
dtypes: float64(2), int32(1), object(6)
memory usage: 2.1+ KB

In [64]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20M,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10M,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20M,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10M,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+

In [66]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
25,App_26,Productivity,1.8,5113,20M,"1,000+",Paid,9.99,Everyone 10+
26,App_27,Productivity,2.3,5501,20M,"10,000+",Paid,1.99,Teen
27,App_28,Health,1.1,7424,Varies with device,"1,000+",Free,1.99,Everyone 10+
28,App_29,Health,3.8,3542,10M,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,Varies with device,"1,000+",Paid,0.00,Teen

In [68]:
# Additional Steps
# Step 2: Remove duplicates based on the 'App' column
df = df.drop_duplicates(subset=['App'])

In [70]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20M,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10M,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20M,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10M,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+
5,App_6,Productivity,4.7,5331,10M,"100,000+",Free,5.99,Mature 17+
6,App_7,Game,1.0,938,10M,"50,000+",Free,2.99,Everyone
7,App_8,Productivity,2.0,1916,10M,"100,000+",Free,4.99,Everyone
8,App_9,Health,1.1,1594,20M,"50,000+",Free,4.99,Mature 17+
9,App_10,Game,1.3,2356,20M,"50,000+",Paid,0.00,Everyone 10+
10,App_11,Game,1.8,1285,20M,"100,000+",Free,9.99,Teen
11,App_12,Game,4.2,4672,10M,"10,000+",Paid,1.99,Everyone 10+
12,App_13,Productivity,1.5,8249,20M,"10,000+",Paid,9.99,Everyone
13,App_14,Health,2.3,7288,20M,"50,000+",Free,9.99,Teen
14,App_15,Game,3.3,9398,30M,"10,000+",Paid,1.99,Teen
15,App_16,Productivity,3.1,1551,30M,"100,000+",Paid,0.00,Teen
16,App_17,Productivity,2.6,7570,30M,"100,000+",Paid,2.99,Everyone
17,App_18,Health,3.7,9058,10M,"1,000+",Free,2.99,Teen
18,App_19,Productivity,1.2,8800,10M,"10,000+",Paid,2.99,Everyone
19,App_20,Game,2.4,6859,30M,"50,000+",Free,1.99,Mature 17+
20,App_21,Education,3.6,5304,20M,"10,000+",Paid,0.00,Everyone
21,App_22,Health,3.7,5337,20M,"100,000+",Paid,5.99,Everyone
22,App_23,Education,2.7,394,20M,"100,000+",Paid,0.00,Teen
23,App_24,Education,1.7,3377,10M,"10,000+",Paid,0.00,Teen
24,App_25,Health,2.4,6924,20M,"1,000+",Paid,0.99,Everyone 10+
25,App_26,Productivity,1.8,5113,20M,"1,000+",Paid,9.99,Everyone 10+
26,App_27,Productivity,2.3,5501,20M,"10,000+",Paid,1.99,Teen
27,App_28,Health,1.1,7424,Varies with device,"1,000+",Free,1.99,Everyone 10+
28,App_29,Health,3.8,3542,10M,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,Varies with device,"1,000+",Paid,0.00,Teen

In [74]:
df['Size'].unique()

array(['20M', '10M', 'Varies with device', '30M'], dtype=object)

In [80]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20M,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10M,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20M,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10M,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,Varies with device,"50,000+",Free,4.99,Everyone 10+

In [82]:
# Step 5: Simplify 'Size' column (replace 'Varies with device' with NaN)
df['Size'] = df['Size'].replace('Varies with device', np.nan)

In [84]:
df.head()

     App   Category  Rating  Reviews Size Installs  Type  Price Content Rating
0  App_1  Education     5.0     5112  20M  50,000+  Free   0.99     Mature 17+
1  App_2  Education     4.8     6388  10M  10,000+  Free   9.99           Teen
2  App_3  Education     2.2      881  20M   1,000+  Free   2.99           Teen
3  App_4  Education     2.7     6535  10M  50,000+  Free   9.99     Mature 17+
4  App_5  Education     1.1     3464  NaN  50,000+  Free   4.99   Everyone 10+

In [88]:
df["Size"]

0     20M
1     10M
2     20M
3     10M
4     NaN
5     10M
6     10M
7     10M
8     20M
9     20M
10    20M
11    10M
12    20M
13    20M
14    30M
15    30M
16    30M
17    10M
18    10M
19    30M
20    20M
21    20M
22    20M
23    10M
24    20M
25    20M
26    20M
27    NaN
28    10M
29    NaN
Name: Size, dtype: object

In [90]:
# Step 6: Convert 'Size' from string to numeric (assume 'M' means MB)
df['Size'] = df['Size'].str.replace('M', '').astype(float)

In [92]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,NaN,"50,000+",Free,4.99,Everyone 10+

In [94]:
df['Size']

0     20.0
1     10.0
2     20.0
3     10.0
4      NaN
5     10.0
6     10.0
7     10.0
8     20.0
9     20.0
10    20.0
11    10.0
12    20.0
13    20.0
14    30.0
15    30.0
16    30.0
17    10.0
18    10.0
19    30.0
20    20.0
21    20.0
22    20.0
23    10.0
24    20.0
25    20.0
26    20.0
27     NaN
28    10.0
29     NaN
Name: Size, dtype: float64

In [96]:
# Step 7: Fill missing values in 'Size' with the median size
df['Size'] = df['Size'].fillna(df['Size'].median())

In [98]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+

In [112]:
df["Size"]

0     20.0
1     10.0
2     20.0
3     10.0
4     20.0
5     10.0
6     10.0
7     10.0
8     20.0
9     20.0
10    20.0
11    10.0
12    20.0
13    20.0
14    30.0
15    30.0
16    30.0
17    10.0
18    10.0
19    30.0
20    20.0
21    20.0
22    20.0
23    10.0
24    20.0
25    20.0
26    20.0
27    20.0
28    10.0
29    20.0
Name: Size, dtype: float64

In [114]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+
5,App_6,Productivity,4.7,5331,10.0,"100,000+",Free,5.99,Mature 17+
6,App_7,Game,1.0,938,10.0,"50,000+",Free,2.99,Everyone
7,App_8,Productivity,2.0,1916,10.0,"100,000+",Free,4.99,Everyone
8,App_9,Health,1.1,1594,20.0,"50,000+",Free,4.99,Mature 17+
9,App_10,Game,1.3,2356,20.0,"50,000+",Paid,0.00,Everyone 10+
10,App_11,Game,1.8,1285,20.0,"100,000+",Free,9.99,Teen
11,App_12,Game,4.2,4672,10.0,"10,000+",Paid,1.99,Everyone 10+
12,App_13,Productivity,1.5,8249,20.0,"10,000+",Paid,9.99,Everyone
13,App_14,Health,2.3,7288,20.0,"50,000+",Free,9.99,Teen
14,App_15,Game,3.3,9398,30.0,"10,000+",Paid,1.99,Teen
15,App_16,Productivity,3.1,1551,30.0,"100,000+",Paid,0.00,Teen
16,App_17,Productivity,2.6,7570,30.0,"100,000+",Paid,2.99,Everyone
17,App_18,Health,3.7,9058,10.0,"1,000+",Free,2.99,Teen
18,App_19,Productivity,1.2,8800,10.0,"10,000+",Paid,2.99,Everyone
19,App_20,Game,2.4,6859,30.0,"50,000+",Free,1.99,Mature 17+
20,App_21,Education,3.6,5304,20.0,"10,000+",Paid,0.00,Everyone
21,App_22,Health,3.7,5337,20.0,"100,000+",Paid,5.99,Everyone
22,App_23,Education,2.7,394,20.0,"100,000+",Paid,0.00,Teen
23,App_24,Education,1.7,3377,10.0,"10,000+",Paid,0.00,Teen
24,App_25,Health,2.4,6924,20.0,"1,000+",Paid,0.99,Everyone 10+
25,App_26,Productivity,1.8,5113,20.0,"1,000+",Paid,9.99,Everyone 10+
26,App_27,Productivity,2.3,5501,20.0,"10,000+",Paid,1.99,Teen
27,App_28,Health,1.1,7424,20.0,"1,000+",Free,1.99,Everyone 10+
28,App_29,Health,3.8,3542,10.0,"10,000+",Free,0.99,Everyone
29,App_30,Education,4.3,4187,20.0,"1,000+",Paid,0.00,Teen

In [116]:
# Step 11: Create a new column 'Popularity' based on 'Rating' and 'Reviews'
df['Popularity'] = df['Rating'] * df['Reviews']

In [118]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen,1938.2
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+,17644.5
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+,3810.4
5,App_6,Productivity,4.7,5331,10.0,"100,000+",Free,5.99,Mature 17+,25055.7
6,App_7,Game,1.0,938,10.0,"50,000+",Free,2.99,Everyone,938.0
7,App_8,Productivity,2.0,1916,10.0,"100,000+",Free,4.99,Everyone,3832.0
8,App_9,Health,1.1,1594,20.0,"50,000+",Free,4.99,Mature 17+,1753.4
9,App_10,Game,1.3,2356,20.0,"50,000+",Paid,0.00,Everyone 10+,3062.8
10,App_11,Game,1.8,1285,20.0,"100,000+",Free,9.99,Teen,2313.0
11,App_12,Game,4.2,4672,10.0,"10,000+",Paid,1.99,Everyone 10+,19622.4
12,App_13,Productivity,1.5,8249,20.0,"10,000+",Paid,9.99,Everyone,12373.5
13,App_14,Health,2.3,7288,20.0,"50,000+",Free,9.99,Teen,16762.4
14,App_15,Game,3.3,9398,30.0,"10,000+",Paid,1.99,Teen,31013.4
15,App_16,Productivity,3.1,1551,30.0,"100,000+",Paid,0.00,Teen,4808.1
16,App_17,Productivity,2.6,7570,30.0,"100,000+",Paid,2.99,Everyone,19682.0
17,App_18,Health,3.7,9058,10.0,"1,000+",Free,2.99,Teen,33514.6
18,App_19,Productivity,1.2,8800,10.0,"10,000+",Paid,2.99,Everyone,10560.0
19,App_20,Game,2.4,6859,30.0,"50,000+",Free,1.99,Mature 17+,16461.6
20,App_21,Education,3.6,5304,20.0,"10,000+",Paid,0.00,Everyone,19094.4
21,App_22,Health,3.7,5337,20.0,"100,000+",Paid,5.99,Everyone,19746.9
22,App_23,Education,2.7,394,20.0,"100,000+",Paid,0.00,Teen,1063.8
23,App_24,Education,1.7,3377,10.0,"10,000+",Paid,0.00,Teen,5740.9
24,App_25,Health,2.4,6924,20.0,"1,000+",Paid,0.99,Everyone 10+,16617.6
25,App_26,Productivity,1.8,5113,20.0,"1,000+",Paid,9.99,Everyone 10+,9203.4
26,App_27,Productivity,2.3,5501,20.0,"10,000+",Paid,1.99,Teen,12652.3
27,App_28,Health,1.1,7424,20.0,"1,000+",Free,1.99,Everyone 10+,8166.4
28,App_29,Health,3.8,3542,10.0,"10,000+",Free,0.99,Everyone,13459.6
29,App_30,Education,4.3,4187,20.0,"1,000+",Paid,0.00,Teen,18004.1

In [122]:
df.sort_values(by=['Popularity','Size'], ascending=False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity
17,App_18,Health,3.7,9058,10.0,"1,000+",Free,2.99,Teen,33514.6
14,App_15,Game,3.3,9398,30.0,"10,000+",Paid,1.99,Teen,31013.4
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0
5,App_6,Productivity,4.7,5331,10.0,"100,000+",Free,5.99,Mature 17+,25055.7
21,App_22,Health,3.7,5337,20.0,"100,000+",Paid,5.99,Everyone,19746.9
16,App_17,Productivity,2.6,7570,30.0,"100,000+",Paid,2.99,Everyone,19682.0
11,App_12,Game,4.2,4672,10.0,"10,000+",Paid,1.99,Everyone 10+,19622.4
20,App_21,Education,3.6,5304,20.0,"10,000+",Paid,0.00,Everyone,19094.4
29,App_30,Education,4.3,4187,20.0,"1,000+",Paid,0.00,Teen,18004.1
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+,17644.5
13,App_14,Health,2.3,7288,20.0,"50,000+",Free,9.99,Teen,16762.4
24,App_25,Health,2.4,6924,20.0,"1,000+",Paid,0.99,Everyone 10+,16617.6
19,App_20,Game,2.4,6859,30.0,"50,000+",Free,1.99,Mature 17+,16461.6
28,App_29,Health,3.8,3542,10.0,"10,000+",Free,0.99,Everyone,13459.6
26,App_27,Productivity,2.3,5501,20.0,"10,000+",Paid,1.99,Teen,12652.3
12,App_13,Productivity,1.5,8249,20.0,"10,000+",Paid,9.99,Everyone,12373.5
18,App_19,Productivity,1.2,8800,10.0,"10,000+",Paid,2.99,Everyone,10560.0
25,App_26,Productivity,1.8,5113,20.0,"1,000+",Paid,9.99,Everyone 10+,9203.4
27,App_28,Health,1.1,7424,20.0,"1,000+",Free,1.99,Everyone 10+,8166.4
23,App_24,Education,1.7,3377,10.0,"10,000+",Paid,0.00,Teen,5740.9
15,App_16,Productivity,3.1,1551,30.0,"100,000+",Paid,0.00,Teen,4808.1
7,App_8,Productivity,2.0,1916,10.0,"100,000+",Free,4.99,Everyone,3832.0
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+,3810.4
9,App_10,Game,1.3,2356,20.0,"50,000+",Paid,0.00,Everyone 10+,3062.8
10,App_11,Game,1.8,1285,20.0,"100,000+",Free,9.99,Teen,2313.0
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen,1938.2
8,App_9,Health,1.1,1594,20.0,"50,000+",Free,4.99,Mature 17+,1753.4
22,App_23,Education,2.7,394,20.0,"100,000+",Paid,0.00,Teen,1063.8
6,App_7,Game,1.0,938,10.0,"50,000+",Free,2.99,Everyone,938.0

In [124]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen,1938.2
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+,17644.5
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+,3810.4

In [126]:
#seeeing data of single application
df[df['App']=="App_1"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0

In [128]:
df[df['App']=="App_2"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4

In [130]:
len(df[(df['Type'] == 'Paid') & (df['Price'] < 2.00)])

10

In [132]:
# Check and categorize paid apps
df['Affordable'] = np.where(df['Type'] == 'Paid', np.where(df['Price'] < 5.00, 'Yes', 'No'), 'N/A')

In [134]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity,Affordable
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0,N/A
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4,N/A
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen,1938.2,N/A
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+,17644.5,N/A
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+,3810.4,N/A
5,App_6,Productivity,4.7,5331,10.0,"100,000+",Free,5.99,Mature 17+,25055.7,N/A
6,App_7,Game,1.0,938,10.0,"50,000+",Free,2.99,Everyone,938.0,N/A
7,App_8,Productivity,2.0,1916,10.0,"100,000+",Free,4.99,Everyone,3832.0,N/A
8,App_9,Health,1.1,1594,20.0,"50,000+",Free,4.99,Mature 17+,1753.4,N/A
9,App_10,Game,1.3,2356,20.0,"50,000+",Paid,0.00,Everyone 10+,3062.8,Yes
10,App_11,Game,1.8,1285,20.0,"100,000+",Free,9.99,Teen,2313.0,N/A
11,App_12,Game,4.2,4672,10.0,"10,000+",Paid,1.99,Everyone 10+,19622.4,Yes
12,App_13,Productivity,1.5,8249,20.0,"10,000+",Paid,9.99,Everyone,12373.5,No
13,App_14,Health,2.3,7288,20.0,"50,000+",Free,9.99,Teen,16762.4,N/A
14,App_15,Game,3.3,9398,30.0,"10,000+",Paid,1.99,Teen,31013.4,Yes
15,App_16,Productivity,3.1,1551,30.0,"100,000+",Paid,0.00,Teen,4808.1,Yes
16,App_17,Productivity,2.6,7570,30.0,"100,000+",Paid,2.99,Everyone,19682.0,Yes
17,App_18,Health,3.7,9058,10.0,"1,000+",Free,2.99,Teen,33514.6,N/A
18,App_19,Productivity,1.2,8800,10.0,"10,000+",Paid,2.99,Everyone,10560.0,Yes
19,App_20,Game,2.4,6859,30.0,"50,000+",Free,1.99,Mature 17+,16461.6,N/A
20,App_21,Education,3.6,5304,20.0,"10,000+",Paid,0.00,Everyone,19094.4,Yes
21,App_22,Health,3.7,5337,20.0,"100,000+",Paid,5.99,Everyone,19746.9,No
22,App_23,Education,2.7,394,20.0,"100,000+",Paid,0.00,Teen,1063.8,Yes
23,App_24,Education,1.7,3377,10.0,"10,000+",Paid,0.00,Teen,5740.9,Yes
24,App_25,Health,2.4,6924,20.0,"1,000+",Paid,0.99,Everyone 10+,16617.6,Yes
25,App_26,Productivity,1.8,5113,20.0,"1,000+",Paid,9.99,Everyone 10+,9203.4,No
26,App_27,Productivity,2.3,5501,20.0,"10,000+",Paid,1.99,Teen,12652.3,Yes
27,App_28,Health,1.1,7424,20.0,"1,000+",Free,1.99,Everyone 10+,8166.4,N/A
28,App_29,Health,3.8,3542,10.0,"10,000+",Free,0.99,Everyone,13459.6,N/A
29,App_30,Education,4.3,4187,20.0,"1,000+",Paid,0.00,Teen,18004.1,Yes

In [136]:
# Display the DataFrame
print(df)

       App      Category  Rating  Reviews  Size  Installs  Type  Price  \
0    App_1     Education     5.0     5112  20.0   50,000+  Free   0.99
1    App_2     Education     4.8     6388  10.0   10,000+  Free   9.99
2    App_3     Education     2.2      881  20.0    1,000+  Free   2.99
3    App_4     Education     2.7     6535  10.0   50,000+  Free   9.99
4    App_5     Education     1.1     3464  20.0   50,000+  Free   4.99
5    App_6  Productivity     4.7     5331  10.0  100,000+  Free   5.99
6    App_7          Game     1.0      938  10.0   50,000+  Free   2.99
7    App_8  Productivity     2.0     1916  10.0  100,000+  Free   4.99
8    App_9        Health     1.1     1594  20.0   50,000+  Free   4.99
9   App_10          Game     1.3     2356  20.0   50,000+  Paid   0.00
10  App_11          Game     1.8     1285  20.0  100,000+  Free   9.99
11  App_12          Game     4.2     4672  10.0   10,000+  Paid   1.99
12  App_13  Productivity     1.5     8249  20.0   10,000+  Paid   9.99
13  App_14        Health     2.3     7288  20.0   50,000+  Free   9.99
14  App_15          Game     3.3     9398  30.0   10,000+  Paid   1.99
15  App_16  Productivity     3.1     1551  30.0  100,000+  Paid   0.00
16  App_17  Productivity     2.6     7570  30.0  100,000+  Paid   2.99
17  App_18        Health     3.7     9058  10.0    1,000+  Free   2.99
18  App_19  Productivity     1.2     8800  10.0   10,000+  Paid   2.99
19  App_20          Game     2.4     6859  30.0   50,000+  Free   1.99
20  App_21     Education     3.6     5304  20.0   10,000+  Paid   0.00
21  App_22        Health     3.7     5337  20.0  100,000+  Paid   5.99
22  App_23     Education     2.7      394  20.0  100,000+  Paid   0.00
23  App_24     Education     1.7     3377  10.0   10,000+  Paid   0.00
24  App_25        Health     2.4     6924  20.0    1,000+  Paid   0.99
25  App_26  Productivity     1.8     5113  20.0    1,000+  Paid   9.99
26  App_27  Productivity     2.3     5501  20.0   10,000+  Paid   1.99
27  App_28        Health     1.1     7424  20.0    1,000+  Free   1.99
28  App_29        Health     3.8     3542  10.0   10,000+  Free   0.99
29  App_30     Education     4.3     4187  20.0    1,000+  Paid   0.00

   Content Rating  Popularity Affordable
0      Mature 17+     25560.0        N/A
1            Teen     30662.4        N/A
2            Teen      1938.2        N/A
3      Mature 17+     17644.5        N/A
4    Everyone 10+      3810.4        N/A
5      Mature 17+     25055.7        N/A
6        Everyone       938.0        N/A
7        Everyone      3832.0        N/A
8      Mature 17+      1753.4        N/A
9    Everyone 10+      3062.8        Yes
10           Teen      2313.0        N/A
11   Everyone 10+     19622.4        Yes
12       Everyone     12373.5         No
13           Teen     16762.4        N/A
14           Teen     31013.4        Yes
15           Teen      4808.1        Yes
16       Everyone     19682.0        Yes
17           Teen     33514.6        N/A
18       Everyone     10560.0        Yes
19     Mature 17+     16461.6        N/A
20       Everyone     19094.4        Yes
21       Everyone     19746.9         No
22           Teen      1063.8        Yes
23           Teen      5740.9        Yes
24   Everyone 10+     16617.6        Yes
25   Everyone 10+      9203.4         No
26           Teen     12652.3        Yes
27   Everyone 10+      8166.4        N/A
28       Everyone     13459.6        N/A
29           Teen     18004.1        Yes

In [138]:
df.to_csv('PGD_Google_APP_Data.csv')

In [140]:
df.to_excel('PGD_Google_APP_Data.xlsx')

In [142]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Popularity,Affordable
0,App_1,Education,5.0,5112,20.0,"50,000+",Free,0.99,Mature 17+,25560.0,N/A
1,App_2,Education,4.8,6388,10.0,"10,000+",Free,9.99,Teen,30662.4,N/A
2,App_3,Education,2.2,881,20.0,"1,000+",Free,2.99,Teen,1938.2,N/A
3,App_4,Education,2.7,6535,10.0,"50,000+",Free,9.99,Mature 17+,17644.5,N/A
4,App_5,Education,1.1,3464,20.0,"50,000+",Free,4.99,Everyone 10+,3810.4,N/A
5,App_6,Productivity,4.7,5331,10.0,"100,000+",Free,5.99,Mature 17+,25055.7,N/A
6,App_7,Game,1.0,938,10.0,"50,000+",Free,2.99,Everyone,938.0,N/A
7,App_8,Productivity,2.0,1916,10.0,"100,000+",Free,4.99,Everyone,3832.0,N/A
8,App_9,Health,1.1,1594,20.0,"50,000+",Free,4.99,Mature 17+,1753.4,N/A
9,App_10,Game,1.3,2356,20.0,"50,000+",Paid,0.00,Everyone 10+,3062.8,Yes
10,App_11,Game,1.8,1285,20.0,"100,000+",Free,9.99,Teen,2313.0,N/A
11,App_12,Game,4.2,4672,10.0,"10,000+",Paid,1.99,Everyone 10+,19622.4,Yes
12,App_13,Productivity,1.5,8249,20.0,"10,000+",Paid,9.99,Everyone,12373.5,No
13,App_14,Health,2.3,7288,20.0,"50,000+",Free,9.99,Teen,16762.4,N/A
14,App_15,Game,3.3,9398,30.0,"10,000+",Paid,1.99,Teen,31013.4,Yes
15,App_16,Productivity,3.1,1551,30.0,"100,000+",Paid,0.00,Teen,4808.1,Yes
16,App_17,Productivity,2.6,7570,30.0,"100,000+",Paid,2.99,Everyone,19682.0,Yes
17,App_18,Health,3.7,9058,10.0,"1,000+",Free,2.99,Teen,33514.6,N/A
18,App_19,Productivity,1.2,8800,10.0,"10,000+",Paid,2.99,Everyone,10560.0,Yes
19,App_20,Game,2.4,6859,30.0,"50,000+",Free,1.99,Mature 17+,16461.6,N/A
20,App_21,Education,3.6,5304,20.0,"10,000+",Paid,0.00,Everyone,19094.4,Yes
21,App_22,Health,3.7,5337,20.0,"100,000+",Paid,5.99,Everyone,19746.9,No
22,App_23,Education,2.7,394,20.0,"100,000+",Paid,0.00,Teen,1063.8,Yes
23,App_24,Education,1.7,3377,10.0,"10,000+",Paid,0.00,Teen,5740.9,Yes
24,App_25,Health,2.4,6924,20.0,"1,000+",Paid,0.99,Everyone 10+,16617.6,Yes
25,App_26,Productivity,1.8,5113,20.0,"1,000+",Paid,9.99,Everyone 10+,9203.4,No
26,App_27,Productivity,2.3,5501,20.0,"10,000+",Paid,1.99,Teen,12652.3,Yes
27,App_28,Health,1.1,7424,20.0,"1,000+",Free,1.99,Everyone 10+,8166.4,N/A
28,App_29,Health,3.8,3542,10.0,"10,000+",Free,0.99,Everyone,13459.6,N/A
29,App_30,Education,4.3,4187,20.0,"1,000+",Paid,0.00,Teen,18004.1,Yes

PGD-Python-DS-AI-Batch-7/Notebooks/Week6 /sample Google Play Store data.ipynb